// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajbijowqqejnlvfudkte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqYmlqb3dxcWVqbmx2ZnVka3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTQ1MjUsImV4cCI6MjA3MzY5MDUyNX0.k5ezVcSHtfXBdPjmjZoZPSeXEt3JdJOLGXTnHJbO97U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});